// redux-todos/src/components/Foot.jsx
import React from 'react';

export default class Foot extends React.Component {
  changeVisibility(e) {
    this.props.changeVisibility(e.target.textContent.trim());
  }
  render() {
    const {footStyle, delSelectedTodos, selectedCount, visibility, changeVisibility} = this.props,
      viss = ['全部', '被选中的', '未被选中的'];
    return (
      <div className='foot' style={{display: footStyle}}>
        <i className='foot-del' onClick={delSelectedTodos}>&times;</i>
        <span className='foot-info'> <span className='foot-count'>{selectedCount}</span> 项被选中</span>
        <span className='foot-visibility'>
        {
          viss.map( vis => {
            let className = vis == visibility ? 'foot-visibility-in' : null;
            return (
              <span 
                className={className} 
                onClick={e=>this.changeVisibility(e)} 
                key={vis}>
                {vis}&nbsp;
              </span>
            );
          })
        }
        </span>
      </div>
    )
  }
}

// vuex-todos/src/components/foot.vue
<template>
  <div class="foot">
    <i class="foot-del" @click="delSelectedTodos">&times; </i>
    <span class="foot-info">
      <span class="foot-count">{{selectedLength}}</span> 项被选中
    </span>
    <span class="foot-visibility">
      <span :class="{'foot-visibility-in': visibility==='all'}" @click="changeVisibility('all')">全部</span>
      <span :class="{'foot-visibility-in': visibility==='selected'}" @click="changeVisibility('selected')">被选中的</span>
      <span :class="{'foot-visibility-in': visibility==='unselected'}" @click="changeVisibility('unselected')">未被选中的</span>      
    </span>
  </div>
</template>

<script>
  import { delSelectedTodos, changeVisibility} from '../vuex/actions'
  export default{
    vuex: {
      getters: {
        todos: state => state.todos,
        visibility: state => state.visibility,
      },
      actions: {
        delSelectedTodos,
        changeVisibility
      }
    },
    computed: {
      selectedLength () {
        return this.todos.filter( todo => todo.selected ).length
      }
    }
  }
</script>
