// vuex-todos/src/components/todo.vue
<template>
  <div 
      class="body-item"
      transition="fade"
      @mouseenter="toggleMouseEnter(true)"
      @mouseleave="toggleMouseEnter(false)">
    <i 
      class="round" 
      :class="{'round-selected':todo.selected}" 
      @click="toggle(index)"></i>
    <div 
      class="body-label"
      :class="{'body-label-selected':todo.selected}"
      @click="tryEdit">{{todo.text}}</div>
    <input 
      type="text" 
      class="body-input"
      :class="{'body-input-show':isInputShow}"
      @keydown.enter="submitEdit"
      @blur="submitEdit">
    <i 
      class="body-del" 
      v-show="isMouseEnter"
      @click="delTodo(index)">&times;</i>
  </div>
</template>

<script>
  import { delTodo, toggle, changeText } from '../vuex/actions'
  export default {
    props: ['todo', 'index'],
    data() { return {
      isMouseEnter: false,
      isInputShow: false
    }},
    vuex: {
      getters: {
        todos: state => state.todos
      },
      actions: {
        delTodo, 
        toggle,
        changeText
      }
    },
    methods: {
      toggleMouseEnter (bool) {
        this.isMouseEnter = bool
      },
      tryEdit (e) {
        this.isInputShow = true
        this.$nextTick(() => {
          var input = e.target.nextElementSibling
          input.value = this.todo.text
          input.focus()
          input.select()
        })
      },
      submitEdit (e) {
        if (e.target.value.trim()) {
          this.changeText(this.index, e.target.value.trim())
          this.isInputShow = false
        } else {
          this.delTodo(this.index)
        }
      }
    }
  }
</script>

// redux-todos/src/components/Todo.jsx
import React from 'react';

export default class Todo extends React.Component {
   constructor(props) {
    super(props);
    this.state = {delShow: 'none'};
  } 
  todoDelShow() {
    this.setState({delShow: 'block'});
  }
  todoDelHide() {
    this.setState({delShow: 'none'}); 
  }
  tryEdit(e) {
    let input = e.target.nextSibling;
    input.value = e.target.innerHTML;
    input.style.display = 'inline-block';
    input.select();
    input.focus();
  }
  submitEdit(e, index) {
    if (e.type == 'keydown') {
      if (e.keyCode === 13) e.target.blur();
      return;
    };
    if (e.target.value.trim()) {
      e.target.style.display = 'none';
      this.props.submitEdit(e.target.value, index);
    } else {
      this.props.delTodo(index);
    };
  }
  render() {
    const {index, selected, text, delTodo, toggle} = this.props,
      roundClass = selected ? 'round round-selected' : 'round',
      labelClass = selected ? 'body-label body-label-selected' : 'body-label';
    return (
      <div 
        className='body-item' 
        onMouseEnter={()=>this.todoDelShow()}
        onMouseMove={()=>this.todoDelShow()}
        onMouseLeave={()=>this.todoDelHide()}>
        <i 
          className={roundClass}
          onClick={()=>toggle(index)}
        />
        <div 
          className={labelClass}
          onClick={this.tryEdit}
        >{text}</div>
        <input 
          type='text' 
          className='body-input' 
          style={{display: 'none'}}
          onKeyDown={e=>this.submitEdit(e, index)}
          onBlur={e=>this.submitEdit(e, index)}
        />
        <i 
          className='body-del' 
          style={{display: this.state.delShow}}
          onClick={()=>{delTodo(index)}}
        >&times;</i>
      </div>
    )
  }
};
